
tap_install:
  values:
    shared:
      ingress_domain: "ipillai_gitops_build.tapscale.cloudfocused.in"

    ceip_policy_disclosed: true

    #The above keys are minimum numbers of entries needed in tap-values.yaml to get a functioning TAP Full profile installation.

    # Below are the keys which may have default values set, but can be overridden.

    profile: build # Can take iterate, build, run, view.

    supply_chain: testing # Can take testing, testing_scanning.

    ootb_supply_chain_testing: # Based on supply_chain set above, can be changed to ootb_supply_chain_testing, ootb_supply_chain_testing_scanning.
      registry:
        server: tapscale.azurecr.io/ipillaigitops/build
        repository: workload

    contour:
      envoy:
        service:
          type: LoadBalancer # This is set by default, but can be overridden by setting a different value.

    buildservice:
      kp_default_repository: tapscale.azurecr.io/ipillaigitops/build/buildservice

    ootb_templates:
      iaas_auth: true

    # metadata_store:
    #   ns_for_export_app_cert: "MY-DEV-NAMESPACE" # Verify this namespace is available within your cluster before initiating the Tanzu Application Platform installation.
    #   app_service_type: ClusterIP # Defaults to LoadBalancer. If shared.ingress_domain is set earlier, this must be set to ClusterIP.

    scanning:
      metadataStore:
        url: "" # Configuration is moved, so set this string to empty.
    namespace_provisioner:
#  controller: "false"
      additional_sources:
  # Add templated java scan policy and tekton pipeline
      - git:
          ref: origin/scalability
          subPath: namespace-provisioner-gitops-examples/custom-resources/testing-scanning-supplychain
          url: https://github.com/jsabariganesh/application-accelerator-samples.git
        path: _ytt_lib/testingscanning
