---
tap_install:
  secrets:
    eso:
      aws:
        region: us-west-2
        tap_install_secrets:
          role_arn: arn:aws:iam::752592854961:role/ipillai-gitops-install-build--tap-install-secrets
      remote_refs:
        tap_sensitive_values:
          sensitive_tap_values_yaml:
            key: dev/ipillai-gitops-install-build/tap/sensitive-values.yaml
